AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: 'Example Muster Account Service'
Resources:
  InvoiceService:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: 'com.github.dmozzy.muster.apilambda.MusterLambdaHandler::lambdaEntry'
      Runtime: java8
      CodeUri: ./build/distributions/impl.zip
      Description: ''
      MemorySize: 512
      Timeout: 15
      Role: !Sub "arn:aws:iam::${AWS::AccountId}:role/MusterRole"
      Events:
        PreWarmLambdas:
          Type: Schedule
          Properties:
            Schedule: rate(5 minutes)
      Environment:
        Variables:
          ServiceClasses: com.github.dmozzy.muster.example.invoice.impl.InvoiceServiceImpl
          PreWarmCount: 3
